%% Automate Importing Data by Generating Code Using the Database Explorer App
% This code reproduces the data obtained using the Database Explorer app by
% connecting to a database, executing a SQL query, and importing data into the
% MATLAB(R) workspace. To use this code, add the password for connecting to the
% database in the database command.

% Auto-generated by MATLAB (R2021b) and Database Toolbox Version 10.2 on 28-May-2025 18:34:30

%% Make connection to database
conn = database('ephysDatabase','','');

%Set query to execute on the database
query = ['SELECT tblexperiment.experimentId, tblexperiment.unitNr, tblexperiment.experimentNr, tblrecording.recSite, tblrecording.probeId, tblmanipulation.manipDescr, tblmanipulation.manipDetail, tblexperiment.looperName1, tblexperiment.looperName2, tblexperiment.looperName3 ' ...
    'FROM (((ferretphysiology.tblexperiment ' ...
    'INNER JOIN ferretphysiology.tblanimal ON tblexperiment.experimentId = tblanimal.experimentId) ' ...
    'INNER JOIN ferretphysiology.tblrecording ON tblexperiment.experimentKey = tblrecording.experimentKey) ' ...
    'INNER JOIN ferretphysiology.tblmanipulation ON tblexperiment.experimentKey = tblmanipulation.experimentKey) ' ...
    'WHERE (looperName1 = ''contrast'' OR looperName2 = ''contrast'' OR looperName3 = ''contrast'') ' ...
    'AND manipDescr = ''cooling'' ' ...
    'AND abort = 0 ' ...
    ''];

%% Execute query and fetch results
data = fetch(conn,query);

%% Close connection to database
close(conn)

%% Clear variables
clear conn query