
function [data] = queryCoolV1(ageLims) 

%% Make connection to database
conn = database('ephysDatabase','','');

%Set query to execute on the database
query = ['SELECT tblanimal.age, ' ...
'	tblanimal.rearingCond, ' ...
'	tblexperiment.experimentId, ' ...
'	tblexperiment.unitNr, ' ...
'	tblexperiment.experimentNr, ' ...
'	tblexperiment.module, ' ...
'	tblexperiment.looperNameCond1, ' ...
'	tblexperiment.looperNameCond2, ' ...
'	tblexperiment.looperNameCond3, ' ...
'	tblexperiment.looperNameCond4, ' ...
'	tblexperiment.looperNameCond5, ' ...
'	tblexperiment.duringMFlag, ' ...
'	tblmanipulation.manipDescr, ' ...
'	tblmanipulation.manipDetail, ' ...
'	tblexperiment.priorMFlag, ' ...
'	tblmanipulation.priorDescr, ' ...
'	tblrecording.recSite, ' ...
'	tblrecording.probeId, ' ...
'	tblrecording.penNr ' ...
'FROM ( ( ( ferretphysiology.tblexperiment ' ...
'INNER JOIN ferretphysiology.tblrecording ' ...
'ON tblexperiment.experimentkey = tblrecording.experimentkey)  ' ...
'INNER JOIN ferretphysiology.tblmanipulation ' ...
'ON tblexperiment.experimentkey = tblmanipulation.experimentkey)  ' ...
'INNER JOIN ferretphysiology.tblanimal ' ...
'ON tblexperiment.experimentid = tblanimal.experimentid)  ' ...
'WHERE tblmanipulation.manipDescr = ''Cooling'' ' ...
'	AND tblmanipulation.manipDetail = ''V1'' ' ...
'	AND tblmanipulation.priorDescr != ''Train+Cool'' ' ...
'	AND tblexperiment.abort = 0 ' ...
'	AND tblanimal.age > ' num2str(ageLims(1)) ' ' ...
'	AND tblanimal.age < ' num2str(ageLims(2)) ' ' ...
'	AND tblanimal.rearingCond = ''normal'''];

%% Execute query and fetch results
data = fetch(conn,query);

%% Close connection to database
close(conn)

%% Clear variables
clear conn query

end