function data = V1Cool()

%% Make connection to database
conn = database('ephysDatabase','','');

%Set query to execute on the database
query = ['SELECT tblanimal.experimentId, ' ...
    '	tblexperiment.unitNr, ' ...
    '	tblexperiment.experimentNr, ' ...
    '	tblanimal.age, ' ...
    '	tblanimal.sex, ' ...
    '	tblanimal.rearingCond, ' ...
    '	tblmanipulation.manipDescr, ' ...
    '	tblmanipulation.manipDetail ' ...
    'FROM ( ( ferretphysiology.tblanimal ' ...
    'INNER JOIN ferretphysiology.tblexperiment ' ...
    'ON tblanimal.experimentid = tblexperiment.experimentid)  ' ...
    'INNER JOIN ferretphysiology.tblmanipulation ' ...
    'ON tblexperiment.experimentkey = tblmanipulation.experimentkey)  ' ...
    'WHERE tblmanipulation.manipDescr = ''Cooling'' ' ...
    '	AND tblmanipulation.manipDetail = ''V1'' ' ...
    '	AND tblanimal.rearingCond = ''normal'''];

%% Execute query and fetch results
data = fetch(conn,query);

%% Close connection to database
close(conn)

%% Clear variables
clear conn query

end